#!/bin/python3
# from playsound import playsound
import wget
import bs4
import requests
import shutil
from compara import compara
import os

link = input("Digite o link? ")

fileName = input("Qual a thread das imagens? ")

# Faz o request do site
res = requests.get(link)

# Criando um objeto com bs4 e estruturando em lxml
soup = bs4.BeautifulSoup(res.text, 'lxml')

# Extraindo um elemento do site
link = ''
aux = 0
destination = "/home/arthur/Imagens/4chan/"+fileName
tmp_folder = '/tmp'

# Valida se a pasta existe
if not os.path.exists(destination):
    print('Criando nova pasta para Thread')
    os.mkdir(destination)
else:
    print("Thread já existente. Redirecionando Arquivos")

fileName = fileName + '_'
for div in soup.find_all(class_="fileText", attrs={'href'}):
    aux += 1
    link = "http:"+div.find('a')['href']

    # Divido o nome do arquivo baixado, pego o sufixo
    sufixo = '.' + wget.detect_filename(link).split('.')[-1]
    fileDestination = os.path.join(destination, fileName+str(aux)+sufixo)

    while os.path.isfile(fileDestination):
        aux += 1
        fileDestination = ''
        fileDestination = os.path.join(destination, fileName+str(aux)+sufixo)

    # Salvo o arquivo arquivo como:
    fileTmp = os.path.join(tmp_folder, fileName+str(aux)+sufixo)
    wget.download(link, out=fileTmp)

    # Se nao existe copia
    # Pasta do path / nome da thread arquivo / nome Arquivo + N_Arquivo + sufixo
    compara(fileTmp, destination)

# Successfully downloaded
# playsound('success.m4a')
